# Setup
title:               'juvenalia'
tagline:             'for I shall never grow old'
description:         'writing (largely creative)'
url:                 https://aileenz.com
baseurl:             '/writing'
paginate:            7
permalink:           pretty

# About/contact
author:
  name:              aileen zhang
  url:               https://aileenz.com
  email:             me@aileenz.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
excerpt_separator:   <!--more-->